# Generated by Django 3.0.6 on 2020-07-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('tag', models.TextField()),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('description_3', models.TextField()),
                ('description_4', models.TextField()),
                ('contact_heading', models.TextField()),
                ('git', models.CharField(max_length=300)),
                ('linkedin', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('fb', models.CharField(max_length=300)),
                ('background_img', models.FilePathField(path='/img')),
            ],
        ),
    ]
