# Generated by Django 3.0.6 on 2020-07-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='background_img',
        ),
        migrations.AddField(
            model_name='home',
            name='background_1',
            field=models.FilePathField(default='SOME STRING', path='/img'),
        ),
        migrations.AddField(
            model_name='home',
            name='background_2',
            field=models.FilePathField(default='SOME STRING', path='/img'),
        ),
        migrations.AddField(
            model_name='home',
            name='background_3',
            field=models.FilePathField(default='SOME STRING', path='/img'),
        ),
        migrations.AddField(
            model_name='home',
            name='background_4',
            field=models.FilePathField(default='SOME STRING', path='/img'),
        ),
        migrations.AddField(
            model_name='home',
            name='background_5',
            field=models.FilePathField(default='SOME STRING', path='/img'),
        ),
    ]
