# Generated by Django 3.0.6 on 2020-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200730_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='insta',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='home',
            name='profile_photo',
            field=models.FilePathField(default='SOME STRING', path='/img'),
        ),
        migrations.AlterField(
            model_name='home',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='fb',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='git',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='linkedin',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
    ]
